import { Inter } from "next/font/google";
import "./globals.css";
import DynamicBackground from "@/components/DynamicBackground";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "leyla developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DynamicBackground />
        {children}
      </body>
    </html>
  );
}
